name: Tests

on: [push]

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  integration:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Install dependencies
        uses: bahmutov/npm-install@v1

      # playwright recommends if you cache the binaries to keep it tied to the version of playwright you are using.
      # https://playwright.dev/docs/ci#caching-browsers
      - name: 🕵️‍♂️ Get current Playwright version
        id: playwright-version
        shell: bash
        run: |
          playwright_version=$(npm info @playwright/test version)
          echo "::set-output name=version::${playwright_version}"

      - name: 🤖 Cache Playwright binaries
        uses: actions/cache@v3
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-${{ runner.arch }}-cache-playwright-${{ steps.playwright-version.outputs.version }}

      - name: 🖨️ Playwright info
        shell: bash
        run: |
          echo "OS: ${{ matrix.os }}"
          echo "Playwright version: ${{ steps.playwright-version.outputs.version }}"
          echo "Playwright install dir: ~/.cache/ms-playwright"
          echo "Cache key: ${{ runner.os }}-${{ runner.arch }}-cache-playwright-${{ steps.playwright-version.outputs.version }}"
          echo "Cache hit: ${{ steps.playwright-cache.outputs.cache-hit == 'true' }}"

      - name: 📥 Install Playwright
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npm run test
